"""七网官网新闻：中证网、中国证券网、证券时报网、证券日报网、金融时报网、经济参考网、中国日报网。"""

from company.news.official.press.cs import (
    FIELDS as CS_FIELDS,
    SORTS as CS_SORTS,
    fetch_news as fetch_cs_news,
    query_page as query_cs_page,
    resolve_keyword as resolve_cs_keyword,
    search_news as search_cs_news,
    search_page_url as cs_search_page_url,
)
from company.news.official.press.cnstock import (
    TYPES as CNSTOCK_TYPES,
    fetch_news as fetch_cnstock_news,
    query_page as query_cnstock_page,
    resolve_keyword as resolve_cnstock_keyword,
    search_news as search_cnstock_news,
    search_page_url as cnstock_search_page_url,
)
from company.news.official.press.stcn import (
    SORTS as STCN_SORTS,
    TYPES as STCN_TYPES,
    fetch_news as fetch_stcn_news,
    query_page as query_stcn_page,
    resolve_keyword as resolve_stcn_keyword,
    search_news as search_stcn_news,
    search_page_url as stcn_search_page_url,
)
from company.news.official.press.zqrb import (
    FIELDS as ZQRB_FIELDS,
    SORTS as ZQRB_SORTS,
    SOURCES as ZQRB_SOURCES,
    fetch_news as fetch_zqrb_news,
    query_page as query_zqrb_page,
    resolve_keyword as resolve_zqrb_keyword,
    search_news as search_zqrb_news,
    search_page_url as zqrb_search_page_url,
)
from company.news.official.press.financialnews import (
    FIELDS as FINANCIALNEWS_FIELDS,
    SORTS as FINANCIALNEWS_SORTS,
    fetch_news as fetch_financialnews_news,
    query_page as query_financialnews_page,
    resolve_keyword as resolve_financialnews_keyword,
    search_news as search_financialnews_news,
    search_page_url as financialnews_search_page_url,
)
from company.news.official.press.jjckb import (
    fetch_news as fetch_jjckb_news,
    query_page as query_jjckb_page,
    resolve_keyword as resolve_jjckb_keyword,
    search_news as search_jjckb_news,
    search_page_url as jjckb_search_page_url,
)
from company.news.official.press.chinadaily import (
    SORTS as CHINADAILY_SORTS,
    TYPES as CHINADAILY_TYPES,
    fetch_news as fetch_chinadaily_news,
    query_page as query_chinadaily_page,
    resolve_keyword as resolve_chinadaily_keyword,
    search_news as search_chinadaily_news,
    search_page_url as chinadaily_search_page_url,
)

__all__ = [
    "CHINADAILY_SORTS",
    "CHINADAILY_TYPES",
    "CNSTOCK_TYPES",
    "CS_FIELDS",
    "CS_SORTS",
    "STCN_SORTS",
    "STCN_TYPES",
    "FINANCIALNEWS_FIELDS",
    "FINANCIALNEWS_SORTS",
    "ZQRB_FIELDS",
    "ZQRB_SORTS",
    "ZQRB_SOURCES",
    "chinadaily_search_page_url",
    "cnstock_search_page_url",
    "cs_search_page_url",
    "financialnews_search_page_url",
    "jjckb_search_page_url",
    "fetch_chinadaily_news",
    "fetch_cnstock_news",
    "fetch_cs_news",
    "fetch_financialnews_news",
    "fetch_jjckb_news",
    "fetch_stcn_news",
    "fetch_zqrb_news",
    "query_chinadaily_page",
    "query_cnstock_page",
    "query_cs_page",
    "query_financialnews_page",
    "query_jjckb_page",
    "query_stcn_page",
    "query_zqrb_page",
    "resolve_chinadaily_keyword",
    "resolve_cnstock_keyword",
    "resolve_cs_keyword",
    "resolve_financialnews_keyword",
    "resolve_jjckb_keyword",
    "resolve_stcn_keyword",
    "resolve_zqrb_keyword",
    "search_chinadaily_news",
    "search_cnstock_news",
    "search_cs_news",
    "search_financialnews_news",
    "search_jjckb_news",
    "search_stcn_news",
    "search_zqrb_news",
    "stcn_search_page_url",
    "zqrb_search_page_url",
]
