"""个股资讯：采集源 + 详情页/画像集成。

采集源：
  - ``cninfo``       巨潮资讯公告
  - ``exchange``     上交所 / 深交所 / 北交所公告
  - ``press``        七网官网新闻（中证网、中国证券网、证券时报网、证券日报网、金融时报网、经济参考网、中国日报网）
  - ``eastmoney``    东方财富（搜索 / 7×24 / 栏目 / F10 / 公告 / 正文）
  - ``tonghuashun``  同花顺（F10 热点新闻 / 公告 / 研报 / 7×24 / 正文）
  - ``xueqiu``       雪球（个股资讯 / 公告 / 研报 / 讨论 / 7×24 / 栏目 / 正文）

集成：
  - ``feed``         详情页分组（``collect_company_messages`` → ``/api/stocks/news``）
  - ``profile``      分类画像（``query_company_profile`` → ``/api/stocks/profile-messages``）
  - ``query``        公告 / 监管 / 七网统一查询
  - ``taxonomy``     category / source_tier / subcategory
"""

from company.news.cninfo import (
    CATEGORIES,
    COLUMNS,
    PLATES,
    TABS,
    a_share_code,
    download_announcements,
    download_pdf,
    fetch_announcements,
    fetch_market_announcements,
    fetch_periodic_reports,
    fetch_supervise,
    fetch_surveys,
    load_org_map,
    pdf_url,
    query_page,
    resolve_org,
    search_announcements,
    search_orgs,
)
from company.news.exchange import (
    BSE_CATEGORIES,
    BSE_LAYERS,
    SECURITY_TYPES,
    SZSE_CATEGORIES,
    SZSE_CHANNELS,
    bse_bulletin_page_url,
    bse_pdf_url,
    bulletin_page_url,
    download_bse_announcements,
    download_bse_pdf,
    download_sse_announcements,
    download_sse_pdf,
    download_szse_announcements,
    download_szse_pdf,
    fetch_bse_all,
    fetch_bse_announcements,
    fetch_bse_inquiries,
    fetch_bse_latest_announcements,
    fetch_bse_periodic_reports,
    fetch_latest_announcements,
    fetch_sse_all,
    fetch_sse_announcements,
    fetch_sse_inquiries,
    fetch_sse_periodic_reports,
    fetch_szse_all,
    fetch_szse_announcements,
    fetch_szse_inquiries,
    fetch_szse_latest_announcements,
    fetch_szse_periodic_reports,
    is_bse_code,
    is_sse_code,
    is_szse_code,
    query_bse_bulletin_page,
    query_bulletin_page,
    query_inquiry_page,
    query_latest_page,
    query_szse_bulletin_page,
    query_szse_inquiry_page,
    search_bse_announcements,
    search_sse_announcements,
    search_szse_announcements,
    sse_pdf_url,
    szse_bulletin_page_url,
    szse_pdf_url,
)
from company.news.press import (
    CHINADAILY_SORTS,
    CHINADAILY_TYPES,
    CNSTOCK_TYPES,
    CS_FIELDS,
    CS_SORTS,
    FINANCIALNEWS_FIELDS,
    FINANCIALNEWS_SORTS,
    STCN_SORTS,
    STCN_TYPES,
    ZQRB_FIELDS,
    ZQRB_SORTS,
    ZQRB_SOURCES,
    chinadaily_search_page_url,
    cnstock_search_page_url,
    cs_search_page_url,
    fetch_chinadaily_news,
    fetch_cnstock_news,
    fetch_cs_news,
    fetch_financialnews_news,
    fetch_jjckb_news,
    fetch_stcn_news,
    fetch_zqrb_news,
    financialnews_search_page_url,
    jjckb_search_page_url,
    query_chinadaily_page,
    query_cnstock_page,
    query_cs_page,
    query_financialnews_page,
    query_jjckb_page,
    query_stcn_page,
    query_zqrb_page,
    resolve_chinadaily_keyword,
    resolve_cnstock_keyword,
    resolve_cs_keyword,
    resolve_financialnews_keyword,
    resolve_jjckb_keyword,
    resolve_stcn_keyword,
    resolve_zqrb_keyword,
    search_chinadaily_news,
    search_cnstock_news,
    search_cs_news,
    search_financialnews_news,
    search_jjckb_news,
    search_stcn_news,
    search_zqrb_news,
    stcn_search_page_url,
    zqrb_search_page_url,
)
from company.news.eastmoney import (
    FLASH_COLUMNS,
    NEWS_COLUMNS,
    article_url as eastmoney_article_url,
    fetch_article as fetch_eastmoney_article,
    fetch_column_news as fetch_eastmoney_column,
    fetch_company as fetch_eastmoney_company,
    fetch_f10 as fetch_eastmoney_f10,
    fetch_flash as fetch_eastmoney_flash,
    fetch_news as fetch_eastmoney_news,
    fetch_notice_content as fetch_eastmoney_notice_content,
    fetch_notices as fetch_eastmoney_notices,
    query_page as query_eastmoney_page,
    resolve_keyword as resolve_eastmoney_keyword,
    search_news as search_eastmoney_news,
    search_page_url as eastmoney_search_page_url,
)
from company.news.tonghuashun import (
    CLASSIFIES as THS_CLASSIFIES,
    article_url as tonghuashun_article_url,
    f10_news_url as tonghuashun_f10_url,
    fetch_article as fetch_tonghuashun_article,
    fetch_company as fetch_tonghuashun_company,
    fetch_flash as fetch_tonghuashun_flash,
    fetch_news as fetch_tonghuashun_news,
    fetch_notices as fetch_tonghuashun_notices,
    fetch_reports as fetch_tonghuashun_reports,
    query_page as query_tonghuashun_page,
    resolve_keyword as resolve_tonghuashun_keyword,
    search_news as search_tonghuashun_news,
    search_page_url as tonghuashun_search_page_url,
    ths_market,
)
from company.news.xueqiu import (
    COLUMNS as XQ_COLUMNS,
    SEARCH_SOURCES as XQ_SEARCH_SOURCES,
    SORTS as XQ_SORTS,
    TIMELINE_SOURCES as XQ_TIMELINE_SOURCES,
    article_url as xueqiu_article_url,
    fetch_article as fetch_xueqiu_article,
    fetch_column_news as fetch_xueqiu_column,
    fetch_company as fetch_xueqiu_company,
    fetch_discuss as fetch_xueqiu_discuss,
    fetch_flash as fetch_xueqiu_flash,
    fetch_news as fetch_xueqiu_news,
    fetch_notices as fetch_xueqiu_notices,
    fetch_reports as fetch_xueqiu_reports,
    query_page as query_xueqiu_page,
    resolve_keyword as resolve_xueqiu_keyword,
    search_news as search_xueqiu_news,
    search_page_url as xueqiu_search_page_url,
    search_posts as search_xueqiu_posts,
    stock_page_url as xueqiu_stock_page_url,
    xq_symbol,
)

from company.news.feed import collect_company_messages, collect_important_news
from company.news.profile import query_company_profile
from company.news.query import (
    query_announcements,
    query_company_messages,
    query_press,
    query_press_flat,
    query_regulatory,
)
from company.news.taxonomy import ALL_SECTIONS, DEFAULT_SECTIONS, classify_item

__all__ = [
    "BSE_CATEGORIES",
    "BSE_LAYERS",
    "CATEGORIES",
    "COLUMNS",
    "CHINADAILY_SORTS",
    "CHINADAILY_TYPES",
    "CNSTOCK_TYPES",
    "CS_FIELDS",
    "CS_SORTS",
    "FLASH_COLUMNS",
    "FINANCIALNEWS_FIELDS",
    "FINANCIALNEWS_SORTS",
    "NEWS_COLUMNS",
    "PLATES",
    "SECURITY_TYPES",
    "STCN_SORTS",
    "STCN_TYPES",
    "ZQRB_FIELDS",
    "ZQRB_SORTS",
    "ZQRB_SOURCES",
    "SZSE_CATEGORIES",
    "SZSE_CHANNELS",
    "TABS",
    "THS_CLASSIFIES",
    "XQ_COLUMNS",
    "XQ_SEARCH_SOURCES",
    "XQ_SORTS",
    "XQ_TIMELINE_SOURCES",
    "a_share_code",
    "bse_bulletin_page_url",
    "bse_pdf_url",
    "chinadaily_search_page_url",
    "cnstock_search_page_url",
    "cs_search_page_url",
    "eastmoney_article_url",
    "eastmoney_search_page_url",
    "tonghuashun_article_url",
    "tonghuashun_f10_url",
    "tonghuashun_search_page_url",
    "xueqiu_article_url",
    "xueqiu_search_page_url",
    "xueqiu_stock_page_url",
    "financialnews_search_page_url",
    "jjckb_search_page_url",
    "stcn_search_page_url",
    "zqrb_search_page_url",
    "bulletin_page_url",
    "download_announcements",
    "download_pdf",
    "download_bse_announcements",
    "download_bse_pdf",
    "download_sse_announcements",
    "download_sse_pdf",
    "download_szse_announcements",
    "download_szse_pdf",
    "fetch_announcements",
    "fetch_bse_all",
    "fetch_bse_announcements",
    "fetch_bse_inquiries",
    "fetch_bse_latest_announcements",
    "fetch_bse_periodic_reports",
    "fetch_chinadaily_news",
    "fetch_cnstock_news",
    "fetch_cs_news",
    "fetch_eastmoney_article",
    "fetch_eastmoney_column",
    "fetch_eastmoney_company",
    "fetch_eastmoney_f10",
    "fetch_eastmoney_flash",
    "fetch_eastmoney_news",
    "fetch_eastmoney_notice_content",
    "fetch_eastmoney_notices",
    "fetch_financialnews_news",
    "fetch_jjckb_news",
    "fetch_stcn_news",
    "fetch_zqrb_news",
    "fetch_latest_announcements",
    "fetch_market_announcements",
    "fetch_periodic_reports",
    "fetch_sse_all",
    "fetch_sse_announcements",
    "fetch_sse_inquiries",
    "fetch_sse_periodic_reports",
    "fetch_supervise",
    "fetch_surveys",
    "fetch_szse_all",
    "fetch_szse_announcements",
    "fetch_szse_inquiries",
    "fetch_szse_latest_announcements",
    "fetch_szse_periodic_reports",
    "fetch_tonghuashun_article",
    "fetch_tonghuashun_company",
    "fetch_tonghuashun_flash",
    "fetch_tonghuashun_news",
    "fetch_tonghuashun_notices",
    "fetch_tonghuashun_reports",
    "fetch_xueqiu_article",
    "fetch_xueqiu_column",
    "fetch_xueqiu_company",
    "fetch_xueqiu_discuss",
    "fetch_xueqiu_flash",
    "fetch_xueqiu_news",
    "fetch_xueqiu_notices",
    "fetch_xueqiu_reports",
    "is_bse_code",
    "is_sse_code",
    "is_szse_code",
    "load_org_map",
    "pdf_url",
    "query_chinadaily_page",
    "query_cnstock_page",
    "query_cs_page",
    "query_eastmoney_page",
    "query_financialnews_page",
    "query_jjckb_page",
    "query_stcn_page",
    "query_zqrb_page",
    "query_bse_bulletin_page",
    "query_bulletin_page",
    "query_inquiry_page",
    "query_latest_page",
    "query_page",
    "query_szse_bulletin_page",
    "query_szse_inquiry_page",
    "query_tonghuashun_page",
    "query_xueqiu_page",
    "resolve_chinadaily_keyword",
    "resolve_cnstock_keyword",
    "resolve_cs_keyword",
    "resolve_eastmoney_keyword",
    "resolve_financialnews_keyword",
    "resolve_jjckb_keyword",
    "resolve_org",
    "resolve_stcn_keyword",
    "resolve_tonghuashun_keyword",
    "resolve_xueqiu_keyword",
    "resolve_zqrb_keyword",
    "ths_market",
    "xq_symbol",
    "search_chinadaily_news",
    "search_cnstock_news",
    "search_cs_news",
    "search_eastmoney_news",
    "search_financialnews_news",
    "search_jjckb_news",
    "search_stcn_news",
    "search_tonghuashun_news",
    "search_xueqiu_news",
    "search_xueqiu_posts",
    "search_zqrb_news",
    "search_announcements",
    "search_bse_announcements",
    "search_orgs",
    "search_sse_announcements",
    "search_szse_announcements",
    "sse_pdf_url",
    "szse_bulletin_page_url",
    "szse_pdf_url",
    "ALL_SECTIONS",
    "DEFAULT_SECTIONS",
    "classify_item",
    "collect_company_messages",
    "collect_important_news",
    "query_announcements",
    "query_company_messages",
    "query_company_profile",
    "query_press",
    "query_press_flat",
    "query_regulatory",
]
