"""巴菲特读表：东财 F10 字段名。"""

from __future__ import annotations

REVENUE_FIELDS = ["TOTALOPERATEREVE", "TOTAL_OPERATE_INCOME", "OPERATE_INCOME_PK"]
NET_PROFIT_FIELDS = ["PARENTNETPROFIT", "PARENT_NETPROFIT"]
DEDUCT_PROFIT_FIELDS = ["KCFJCXSYJLR", "DEDUCT_PARENT_NETPROFIT"]
OCF_FIELDS = ["NETCASH_OPERATE_PK", "NETCASH_OPERATE"]
CAPEX_FIELDS = ["CONSTRUCT_LONG_ASSET"]
EQUITY_FIELDS = ["TOTAL_PARENT_EQUITY", "TOTAL_EQUITY_PK", "TOTAL_EQUITY"]
TOTAL_ASSETS_FIELDS = ["TOTAL_ASSETS_PK", "TOTAL_ASSETS"]
TOTAL_LIAB_FIELDS = ["LIABILITY", "TOTAL_LIABILITIES"]
FIXED_ASSET_FIELDS = ["FIXED_ASSET"]
CIP_FIELDS = ["CIP"]
GOODWILL_FIELDS = ["GOODWILL"]
INTANGIBLE_FIELDS = ["INTANGIBLE_ASSET"]
DIVIDEND_FIELDS = ["ASSIGN_CASH_DIVIDEND", "PREASSIGN_CASH_DIVIDEND"]
DIVIDEND_CASH_FIELDS = ["ASSIGN_DIVIDEND_PORFIT"]
DIVIDEND_DESC_FIELDS = ["ASSIGNDSCRPT", "ASSIGN_DSCRPT", "ASSIGN_DESC"]
SHARE_CAPITAL_FIELDS = ["SHARE_CAPITAL"]
TOTAL_SHARE_FIELDS = ["TOTAL_SHARE", "SHARE_CAPITAL"]
ACCEPT_INVEST_FIELDS = ["ACCEPT_INVEST_CASH"]
ISSUE_BOND_FIELDS = ["ISSUE_BOND"]
RECEIVE_LOAN_FIELDS = ["RECEIVE_LOAN_CASH"]
PAY_DEBT_FIELDS = ["PAY_DEBT_CASH"]
FIN_CF_FIELDS = ["NETCASH_FINANCE_PK", "NETCASH_FINANCE"]
ICF_FIELDS = ["NETCASH_INVEST_PK", "NETCASH_INVEST"]

# 折旧摊销（现金流量表附注）
DA_FA_IR = "FA_IR_DEPR"
DA_OILGAS = "OILGAS_BIOLOGY_DEPR"
DA_IR = "IR_DEPR"
DA_IA = "IA_AMORTIZE"
DA_LPE = "LPE_AMORTIZE"
